### ISSUE TITLE
Menus don't work with Ultracold

### ISSUE THREAD

**Issue by TheDarkAndroid** [Ciastex/ArcadeCoinBugCentral#28]
Title: if you're using Ultracold and get in a menu, the cursor doesn't show and it's like the game is still going in the background.

**Comment by Ciastex** [comment]
quote: "they do work, they are just way too fucking slow"

**Comment by TheDarkAndroid** [comment]
They actually don't, no response from clicking but if I use the movement keys I hear the character walking
