### ISSUE TITLE
BHG is all kinds of broken

### ISSUE THREAD

**Issue by Peter111111111111** [Ciastex/ArcadeCoinBugCentral#32]
the BHG needs 3-5 shots to kill tully on threat level 5 
also the secondary doesn't pull you in anymore

**Comment by WobbleOps** [comment]
The secondary isn't meant to pull you. Also it took me two shots, and on the last shot he was at like 15 health.

**Comment by WobbleOps** [comment]
And while I do appreciate the bug report, try and keep the titles less sensationalized.

THAT GOES FOR YOU TOO, DISCORD USERS. I KNOW YOU CAN SEE THIS YOU DRAMA QUEENS!!!
