### ISSUE TITLE
Ghost Problem

### ISSUE THREAD

**Issue by silent93x** [Ciastex/ArcadeCoinBugCentral#37]
https://imgur.com/a/gXgpCfR, basically the starting effect, remained

**Comment by WobbleOps** [comment]
Did you die? Pretty sure this is already on

**Comment by WobbleOps** [comment]
Like it is already reported. I'm about to go work on it now.

**Comment by silent93x** [comment]
No, I didn't die, I used the ULTRA COLD, and that remained throu all the animation

**Comment by silent93x** [comment]
basically the thing where it splits your screen remained until it finished playing

**Comment by silent93x** [comment]
I can't pull it off again, anyway, I used it, it started splitting my sceen (or whatever it does at the start) and I stopped, I started to walk again, but that effect didn't go away

**Comment by silent93x** [comment]
like you can clearly see the distorsion, I guess it's because the ghost really hates ultra cold, it does have some proble,s
