### ISSUE TITLE
Unlock problem

### ISSUE THREAD

**Issue by silent93x** [Ciastex/ArcadeCoinBugCentral#52]
#### Expected behavior
I go through the orange door less than 10 times in a row and the "Ultra Cold" card is unlocked
   
#### Actual behavior
I can't unlock the "Ultra Cold" card, no matter how many times I go through the door.
  
#### Steps to reproduce
1. Go through the orange door
 
#### Additional information
I tried using all the cards entering the door 5 times with each card, and 10 with the "No Life". I tried on Rogue and Overhaul

**Comment by Ciastex** [comment]
Does it happen after resetting your progress by deleting save data?

**Comment by TieDyeTopHat** [comment]
I can confirm there is no bug here, you just have to run through the door a bunch more times than any other card.
