### ISSUE TITLE
Can't wall-run unless I dash before 

### ISSUE THREAD

**Issue by xvawoozy** [Ciastex/ArcadeCoinBugCentral#53]
#### Expected behavior
*replace this with expected behavior e.g. `It should work like this.`*
   
#### Actual behavior
*replace this with actual behavior e.g. `It actually works like this which is wrong.`*
  
#### Steps to reproduce
1. Replace this
2. with actual steps
3. to reproduce the bug
  
#### Additional information
*This is a place for you to include any videos, screenshots and whatnot. It's completely optional.*

**Comment by TieDyeTopHat** [comment]
Wallrunning is getting reworked in the next update.
