### ISSUE TITLE
Infinitely float upwards while holding a block

### ISSUE THREAD

**Issue by KrusteeBoi** [Ciastex/ArcadeCoinBugCentral#54]
If standing on the flat side of a block then jumping up to a certain limit in the sky you begin to float upwards on the block. 
Here is a short clip of after I got to float up: https://clips.twitch.tv/SincereShinyScorpionThisIsSparta
Additional clip of how to get it started: https://clips.twitch.tv/SneakyPoorToothShazBotstix

**Comment by TieDyeTopHat** [comment]
Known, and actually not a bug.

Andrew decided to leave it in for speedrun strats.
