### ISSUE TITLE
Multiple issues including Clipping through ledges, viewmode gun dissapearing, random objects dissapearing and re-appearing, multiple grappling hooks, and finnaly invisibility.

### ISSUE THREAD

**Issue by oatinaboat** [Ciastex/ArcadeCoinBugCentral#59]
Due to the amount of bugs I am going to report I cannot post them all here and how to do them. I made a video showing all the bugs that I encountered and if they are easy to replicate.
----
https://youtu.be/6I2CWxETyAc
This is the video that shows the bugs I found.

**Comment by WobbleOps** [comment]
I watched your video! However none of these things are problems in the main game or problems in the next update. The demo is pretty outdated /:

Thanks though!
