### ISSUE TITLE
I literally can't play the game :(

### ISSUE THREAD

**Issue by SilentReavus** [Ciastex/ArcadeCoinBugCentral#77]
#### Expected behavior
The game should start after the main menu camera dives into the orange void, right?
   
#### Actual behavior
It just closes the game
  
#### Steps to reproduce
1. Launch GTTOD
2. Acknowledge that the game is early access and will have bugs
3. Press any key to start 'diving' animation at main menu
4. The game literally just closes after that

**Comment by BobTheBob9** [comment]
This is known to be caused by not having Windows 10 N's media feature pack installed.
