### ISSUE TITLE
Glitching through walls, stairs, surfaces

### ISSUE THREAD

**Issue by fabsch2003** [Ciastex/ArcadeCoinBugCentral#78]
#### Expected behavior
just an momentum method
   
#### Actual behavior
glitching through objects
  
#### Steps to reproduce
just made a short, shitty yt vid about it, look in additional information
  
#### Additional information
link to vid:  https://www.youtube.com/watch?v=RJMEJ50YCuI

**Comment by Ciastex** [comment]
#44 already covers this.
