### ISSUE TITLE
Laser pistol not shooting in blue mode, second shot no charge up effect

### ISSUE THREAD

**Issue by fabsch2003** [Ciastex/ArcadeCoinBugCentral#79]
#### Expected behavior
switch to blue mode with rmouse, then just charge and shoot
   
#### Actual behavior
at the first shot, it just does the charge up effect, but doesnt shoot, the following shots arent charging up, only shooting
  
#### Steps to reproduce
1. go into any mode using the speedrun kit
2. switch to blue/alternative mode at the laser pistol
3. click left mouse button
  
#### Additional information
link to yt video: https://www.youtube.com/watch?v=-CISzLrRjgQ

**Comment by Ciastex** [comment]
Laser pistol is getting removed in the next update.
